# Generated by Django 5.1.15 on 2026-09-02 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ErpNextSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                (
                    "base_url",
                    models.URLField(
                        blank=True,
                        help_text="e.g. https://erp.example.com",
                        verbose_name="ERPNext URL",
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=120)),
                ("api_secret", models.CharField(blank=True, max_length=200)),
                ("company", models.CharField(blank=True, max_length=150)),
                (
                    "default_warehouse",
                    models.CharField(
                        blank=True,
                        help_text="ERPNext warehouse name used as fallback.",
                        max_length=150,
                    ),
                ),
                (
                    "sync_mode",
                    models.CharField(
                        choices=[
                            ("DISABLED", "Disabled"),
                            ("PUSH", "One way - push to ERPNext"),
                            ("PULL", "One way - pull from ERPNext"),
                            ("TWO_WAY", "Two way"),
                        ],
                        default="DISABLED",
                        max_length=10,
                    ),
                ),
                ("sync_items", models.BooleanField(default=True)),
                ("sync_categories", models.BooleanField(default=True)),
                ("sync_warehouses", models.BooleanField(default=True)),
                ("sync_stock", models.BooleanField(default=True)),
                ("sync_inward", models.BooleanField(default=False)),
                ("sync_outward", models.BooleanField(default=False)),
                ("sync_transfer", models.BooleanField(default=False)),
                ("verify_ssl", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=30)),
                ("last_connection_ok", models.BooleanField(default=False)),
                ("last_connection_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_connection_message",
                    models.CharField(blank=True, max_length=255),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "ERPNext Settings",
                "verbose_name_plural": "ERPNext Settings",
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push to ERPNext"),
                            ("PULL", "Pull from ERPNext"),
                            ("TEST", "Connection test"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        blank=True,
                        help_text="Item, Warehouse, Stock, Inward, ...",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial"),
                            ("FAILED", "Failed"),
                        ],
                        max_length=8,
                    ),
                ),
                ("records_ok", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("payload_preview", models.TextField(blank=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Log",
                "ordering": ["-created_at"],
            },
        ),
    ]
