# Generated by Django 5.1.15 on 2026-09-02 18:14

import core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Spares Inventory", max_length=150),
                ),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Shown in the app header, login screen and reports. Not printed on barcode labels.",
                        null=True,
                        upload_to="branding/",
                        validators=[core.validators.validate_image_file],
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=64)),
                ("pincode", models.CharField(blank=True, max_length=12)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=64),
                ),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "Company Settings",
                "verbose_name_plural": "Company Settings",
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_negative_stock",
                    models.BooleanField(
                        default=False,
                        help_text="Global default. Individual documents still need the override permission.",
                    ),
                ),
                (
                    "suggest_document_numbers",
                    models.BooleanField(
                        default=True,
                        help_text="Pre-fill the next document number. The user can always overwrite it (document numbers are never forced).",
                    ),
                ),
                (
                    "inward_prefix",
                    models.CharField(blank=True, default="IN-", max_length=16),
                ),
                (
                    "outward_prefix",
                    models.CharField(blank=True, default="OUT-", max_length=16),
                ),
                (
                    "transfer_prefix",
                    models.CharField(blank=True, default="TRF-", max_length=16),
                ),
                (
                    "adjustment_prefix",
                    models.CharField(blank=True, default="ADJ-", max_length=16),
                ),
                (
                    "opening_prefix",
                    models.CharField(blank=True, default="OPN-", max_length=16),
                ),
                ("require_adjustment_approval", models.BooleanField(default=True)),
                ("scanner_auto_focus", models.BooleanField(default=True)),
                ("scanner_beep", models.BooleanField(default=True)),
                (
                    "show_public_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Show current stock on the public QR page.",
                    ),
                ),
                (
                    "show_public_location",
                    models.BooleanField(
                        default=True,
                        help_text="Show warehouse/rack location on the public QR page.",
                    ),
                ),
                ("public_page_enabled", models.BooleanField(default=True)),
                ("low_stock_banner", models.BooleanField(default=True)),
                ("date_format", models.CharField(default="d-m-Y", max_length=20)),
                ("rows_per_page", models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="Backup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=500)),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("SCHEDULED", "Scheduled"),
                            ("PRE_RESTORE", "Automatic pre-restore snapshot"),
                        ],
                        default="MANUAL",
                        max_length=12,
                    ),
                ),
                ("includes_media", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
