# Generated by Django 5.1.15 on 2026-09-02 19:40

from django.db import migrations, models


def hide_internal_figures_on_the_public_page(apps, schema_editor):
    """Existing installs also switch to product-details-only.

    The QR link is public, so stock and location come off the page unless an
    administrator turns them back on deliberately.
    """
    SystemSettings = apps.get_model("core", "SystemSettings")
    SystemSettings.objects.update(show_public_stock=False, show_public_location=False)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="public_page_enabled",
            field=models.BooleanField(
                default=True, verbose_name="Public QR page enabled"
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="show_public_location",
            field=models.BooleanField(
                default=False,
                help_text="Off by default, for the same reason. Staff see the location on the internal scanner and item pages instead.",
                verbose_name="Show warehouse and rack location on the public QR page",
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="show_public_stock",
            field=models.BooleanField(
                default=False,
                help_text="Off by default. The QR link is public - anyone with the sticker can open it, including customers and visitors.",
                verbose_name="Show stock quantity on the public QR page",
            ),
        ),
        migrations.RunPython(hide_internal_figures_on_the_public_page, noop),
    ]
