# Generated by Django 5.1.15 on 2026-09-02 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allowed_warehouses",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to allow all warehouses.",
                related_name="permitted_users",
                to="masters.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Pre-selected in transaction and scanner screens.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_users",
                to="masters.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="denied_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissions revoked from this user even if the role grants them.",
                related_name="denied_users",
                to="accounts.apppermission",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="extra_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Permissions granted on top of the user's role.",
                related_name="granted_users",
                to="accounts.apppermission",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="accounts.apppermission"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.role",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["-timestamp", "action"], name="accounts_au_timesta_ace11a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["object_type", "object_id"],
                name="accounts_au_object__353b30_idx",
            ),
        ),
    ]
