# Generated by Django 5.1.15 on 2026-09-02 18:14

import core.validators
import django.core.validators
import django.db.models.deletion
import items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Text"),
                            ("NUMBER", "Number"),
                            ("DATE", "Date"),
                            ("BOOLEAN", "Yes / No"),
                            ("CHOICE", "Choice list"),
                        ],
                        default="TEXT",
                        max_length=10,
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True, help_text="One option per line, for choice lists."
                    ),
                ),
                ("help_text", models.CharField(blank=True, max_length=200)),
                ("is_required", models.BooleanField(default=False)),
                ("show_on_public_page", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "item_number",
                    models.CharField(
                        db_index=True,
                        help_text="Manually entered part number, e.g. SP-001 or BOILER-FD-001.",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9][A-Za-z0-9._\\-/]*$",
                                "Use letters, digits, dot, dash, underscore or slash. Must start with a letter or digit.",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        verbose_name="Manufacturer / Make",
                    ),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "drawing_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "oem_part_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "alternate_part_number",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "material",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("material_grade", models.CharField(blank=True, max_length=100)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(blank=True, default="KG", max_length=16),
                ),
                (
                    "length",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dimension_unit",
                    models.CharField(blank=True, default="MM", max_length=16),
                ),
                ("size", models.CharField(blank=True, max_length=64)),
                (
                    "size_unit",
                    models.CharField(blank=True, default="MM", max_length=16),
                ),
                ("colour", models.CharField(blank=True, max_length=50)),
                (
                    "spare_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MECHANICAL", "Mechanical"),
                            ("ELECTRICAL", "Electrical"),
                            ("INSTRUMENTATION", "Instrumentation"),
                            ("CONSUMABLE", "Consumable"),
                            ("WEAR_PART", "Wear part"),
                            ("ROTABLE", "Rotable / repairable"),
                            ("TOOL", "Tool"),
                            ("FABRICATED", "Fabricated"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        blank=True,
                        help_text="Equipment or system this spare is used on.",
                        max_length=255,
                    ),
                ),
                ("specification", models.TextField(blank=True)),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=16,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "barcode_number",
                    models.CharField(
                        db_index=True,
                        help_text="Defaults to the item number. Encoded as Code 128.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "qr_token",
                    models.CharField(
                        default=items.models.new_qr_token,
                        editable=False,
                        help_text="Opaque token used in the public QR URL.",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Main product image.",
                        null=True,
                        upload_to=items.models.item_primary_image_path,
                        validators=[core.validators.validate_image_file],
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User-defined additional fields.",
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="masters.itemcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Suggested bin for inward of this item.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_items",
                        to="masters.location",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_items",
                        to="masters.itemcategory",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="masters.unitofmeasure",
                        verbose_name="Unit of Measurement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["item_number"],
            },
        ),
        migrations.CreateModel(
            name="ItemDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=items.models.item_document_path,
                        validators=[core.validators.validate_document_file],
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("DRAWING", "Drawing"),
                            ("SPECIFICATION", "Specification"),
                            ("DATASHEET", "Datasheet"),
                            ("MANUAL", "Manual"),
                            ("CERTIFICATE", "Certificate"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=150)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Visible on the public QR page. Keep internal documents private.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="items.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["doc_type", "id"],
            },
        ),
        migrations.CreateModel(
            name="ItemImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=items.models.item_image_path,
                        validators=[core.validators.validate_image_file],
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=150)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="items.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(
                fields=["is_active", "category"], name="items_item_is_acti_089a1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="item",
            index=models.Index(fields=["name"], name="items_item_name_1c746e_idx"),
        ),
    ]
