# Generated by Django 5.1.15 on 2026-09-02 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "width_mm",
                    models.DecimalField(decimal_places=2, default=50, max_digits=6),
                ),
                (
                    "height_mm",
                    models.DecimalField(decimal_places=2, default=25, max_digits=6),
                ),
                ("show_qr", models.BooleanField(default=True)),
                ("show_barcode", models.BooleanField(default=True)),
                ("show_item_number", models.BooleanField(default=True)),
                ("show_item_name", models.BooleanField(default=True)),
                ("show_scan_hint", models.BooleanField(default=True)),
                (
                    "scan_hint_text",
                    models.CharField(
                        default="SCAN TO VIEW PRODUCT DETAILS", max_length=60
                    ),
                ),
                ("show_location", models.BooleanField(default=False)),
                ("item_name_max_chars", models.PositiveSmallIntegerField(default=42)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrinterSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Seznik Mini - Store Counter",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "printer_type",
                    models.CharField(
                        choices=[
                            ("THERMAL_LABEL", "Thermal label printer"),
                            ("THERMAL_RECEIPT", "Thermal receipt printer"),
                            ("LASER", "Laser / inkjet (label sheet)"),
                            ("OTHER", "Other"),
                        ],
                        default="THERMAL_LABEL",
                        max_length=20,
                    ),
                ),
                (
                    "connection_type",
                    models.CharField(
                        choices=[
                            ("USB", "USB"),
                            ("BLUETOOTH", "Bluetooth"),
                            ("NETWORK", "Network / IP"),
                            ("SYSTEM", "Windows / OS printer"),
                            ("BROWSER", "Browser print dialog"),
                        ],
                        default="BROWSER",
                        max_length=12,
                    ),
                ),
                (
                    "system_printer_name",
                    models.CharField(
                        blank=True,
                        help_text="OS printer queue name, if applicable.",
                        max_length=150,
                    ),
                ),
                (
                    "network_address",
                    models.CharField(
                        blank=True,
                        help_text="host:port for network printers.",
                        max_length=120,
                    ),
                ),
                (
                    "label_width_mm",
                    models.DecimalField(decimal_places=2, default=50, max_digits=6),
                ),
                (
                    "label_height_mm",
                    models.DecimalField(decimal_places=2, default=25, max_digits=6),
                ),
                (
                    "label_gap_mm",
                    models.DecimalField(decimal_places=2, default=2, max_digits=5),
                ),
                (
                    "margin_mm",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
                ),
                (
                    "columns_per_row",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Labels side by side across the web. 1 for a roll printer.",
                    ),
                ),
                (
                    "dpi",
                    models.PositiveSmallIntegerField(
                        default=203, help_text="203 dpi (8 dots/mm) is typical."
                    ),
                ),
                (
                    "print_density",
                    models.PositiveSmallIntegerField(
                        default=8, help_text="Darkness, 0-15 on most units."
                    ),
                ),
                (
                    "print_speed",
                    models.PositiveSmallIntegerField(
                        default=4, help_text="Inches per second."
                    ),
                ),
                ("supports_escpos", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabelPrintLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("copies", models.PositiveIntegerField(default=1)),
                ("is_reprint", models.BooleanField(default=False)),
                ("barcode_snapshot", models.CharField(blank=True, max_length=64)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_logs",
                        to="items.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_logs",
                        to="labels.labeltemplate",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_logs",
                        to="labels.printersetting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["item", "-created_at"],
                        name="labels_labe_item_id_805fcb_idx",
                    )
                ],
            },
        ),
    ]
